add_library(libnl
        libnl/lib/cli/cls/basic.c
        libnl/lib/cli/cls/cgroup.c
        libnl/lib/cli/qdisc/bfifo.c
        libnl/lib/cli/qdisc/blackhole.c
        libnl/lib/cli/qdisc/fq_codel.c
        libnl/lib/cli/qdisc/hfsc.c
        libnl/lib/cli/qdisc/htb.c
        libnl/lib/cli/qdisc/ingress.c
        libnl/lib/cli/qdisc/pfifo.c
        libnl/lib/cli/qdisc/plug.c
        libnl/lib/fib_lookup/lookup.c
        libnl/lib/fib_lookup/request.c
        libnl/lib/genl/ctrl.c
        libnl/lib/genl/family.c
        libnl/lib/genl/genl.c
        libnl/lib/genl/mngt.c
        libnl/lib/idiag/idiag.c
        libnl/lib/idiag/idiag_meminfo_obj.c
        libnl/lib/idiag/idiag_msg_obj.c
        libnl/lib/idiag/idiag_req_obj.c
        libnl/lib/idiag/idiag_vegasinfo_obj.c
        libnl/lib/netfilter/ct.c
        libnl/lib/netfilter/ct_obj.c
        libnl/lib/netfilter/exp.c
        libnl/lib/netfilter/exp_obj.c
        libnl/lib/netfilter/log.c
        libnl/lib/netfilter/log_msg.c
        libnl/lib/netfilter/log_msg_obj.c
        libnl/lib/netfilter/log_obj.c
        libnl/lib/netfilter/netfilter.c
        libnl/lib/netfilter/nfnl.c
        libnl/lib/netfilter/queue.c
        libnl/lib/netfilter/queue_msg.c
        libnl/lib/netfilter/queue_msg_obj.c
        libnl/lib/netfilter/queue_obj.c
        libnl/lib/route/act/gact.c
        libnl/lib/route/act/mirred.c
        libnl/lib/route/act/nat.c
        libnl/lib/route/act/skbedit.c
        libnl/lib/route/act/vlan.c
        libnl/lib/route/cls/ematch/cmp.c
        libnl/lib/route/cls/ematch/container.c
        libnl/lib/route/cls/ematch/meta.c
        libnl/lib/route/cls/ematch/nbyte.c
        libnl/lib/route/cls/ematch/text.c
        libnl/lib/route/cls/basic.c
        libnl/lib/route/cls/cgroup.c
        libnl/lib/route/cls/ematch.c
        libnl/lib/route/cls/ematch_grammar.c
        libnl/lib/route/cls/ematch_grammar.h
        libnl/lib/route/cls/ematch_syntax.c
        libnl/lib/route/cls/ematch_syntax.h
        libnl/lib/route/cls/flower.c
        libnl/lib/route/cls/fw.c
        libnl/lib/route/cls/mall.c
        libnl/lib/route/cls/police.c
        libnl/lib/route/cls/u32.c
        libnl/lib/route/link/api.c
        libnl/lib/route/link/bonding.c
        libnl/lib/route/link/bridge.c
        libnl/lib/route/link/bridge_info.c
        libnl/lib/route/link/can.c
        libnl/lib/route/link/dummy.c
        libnl/lib/route/link/geneve.c
        libnl/lib/route/link/ifb.c
        libnl/lib/route/link/inet.c
        libnl/lib/route/link/inet6.c
        libnl/lib/route/link/ip6gre.c
        libnl/lib/route/link/ip6tnl.c
        libnl/lib/route/link/ip6vti.c
        libnl/lib/route/link/ipgre.c
        libnl/lib/route/link/ipip.c
        libnl/lib/route/link/ipvlan.c
        libnl/lib/route/link/ipvti.c
        libnl/lib/route/link/macsec.c
        libnl/lib/route/link/macvlan.c
        libnl/lib/route/link/ppp.c
        libnl/lib/route/link/sit.c
        libnl/lib/route/link/sriov.c
        libnl/lib/route/link/team.c
        libnl/lib/route/link/veth.c
        libnl/lib/route/link/vlan.c
        libnl/lib/route/link/vrf.c
        libnl/lib/route/link/vxlan.c
        libnl/lib/route/link/xfrmi.c
        libnl/lib/route/qdisc/blackhole.c
        libnl/lib/route/qdisc/cbq.c
        libnl/lib/route/qdisc/dsmark.c
        libnl/lib/route/qdisc/fifo.c
        libnl/lib/route/qdisc/fq_codel.c
        libnl/lib/route/qdisc/hfsc.c
        libnl/lib/route/qdisc/htb.c
        libnl/lib/route/qdisc/ingress.c
        libnl/lib/route/qdisc/mqprio.c
        libnl/lib/route/qdisc/netem.c
        libnl/lib/route/qdisc/plug.c
        libnl/lib/route/qdisc/prio.c
        libnl/lib/route/qdisc/red.c
        libnl/lib/route/qdisc/sfq.c
        libnl/lib/route/qdisc/tbf.c
        libnl/lib/route/act.c
        libnl/lib/route/addr.c
        libnl/lib/route/class.c
        libnl/lib/route/classid.c
        libnl/lib/route/cls.c
        libnl/lib/route/link.c
        libnl/lib/route/mdb.c
        libnl/lib/route/neigh.c
        libnl/lib/route/neightbl.c
        libnl/lib/route/netconf.c
        libnl/lib/route/nexthop.c
        libnl/lib/route/nexthop_encap.c
        libnl/lib/route/nh_encap_mpls.c
        libnl/lib/route/pktloc.c
        libnl/lib/route/pktloc_grammar.c
        libnl/lib/route/pktloc_grammar.h
        libnl/lib/route/pktloc_syntax.c
        libnl/lib/route/pktloc_syntax.h
        libnl/lib/route/qdisc.c
        libnl/lib/route/rule.c
        libnl/lib/route/route.c
        libnl/lib/route/route_obj.c
        libnl/lib/route/route_utils.c
        libnl/lib/route/rtnl.c
        libnl/lib/route/tc.c
        libnl/lib/xfrm/ae.c
        libnl/lib/xfrm/lifetime.c
        libnl/lib/xfrm/sa.c
        libnl/lib/xfrm/selector.c
        libnl/lib/xfrm/sp.c
        libnl/lib/xfrm/template.c
        libnl/lib/addr.c
        libnl/lib/attr.c
        libnl/lib/cache.c
        libnl/lib/cache_mngr.c
        libnl/lib/cache_mngt.c
        libnl/lib/data.c
        libnl/lib/defs.h
        libnl/lib/error.c
        libnl/lib/handlers.c
        libnl/lib/hash.c
        libnl/lib/hashtable.c
        libnl/lib/mpls.c
        libnl/lib/msg.c
        libnl/lib/nl.c
        libnl/lib/object.c
        libnl/lib/socket.c
        libnl/lib/utils.c
        libnl/lib/version.c
        libnl/src/lib/addr.c
        libnl/src/lib/class.c
        libnl/src/lib/cls.c
        libnl/src/lib/ct.c
        libnl/src/lib/exp.c
        libnl/src/lib/link.c
        libnl/src/lib/neigh.c
        libnl/src/lib/qdisc.c
        libnl/src/lib/route.c
        libnl/src/lib/rule.c
        libnl/src/lib/tc.c
        libnl/src/lib/utils.c
        libnl/src/genl-ctrl-list.c
        libnl/src/idiag-socket-details.c
        libnl/src/nf-ct-add.c
        libnl/src/nf-ct-events.c
        libnl/src/nf-ct-list.c
        libnl/src/nf-exp-add.c
        libnl/src/nf-exp-delete.c
        libnl/src/nf-exp-list.c
        libnl/src/nf-log.c
        libnl/src/nf-monitor.c
        libnl/src/nf-queue.c
        libnl/src/nl-addr-add.c
        libnl/src/nl-addr-delete.c
        libnl/src/nl-addr-list.c
        libnl/src/nl-class-add.c
        libnl/src/nl-class-delete.c
        libnl/src/nl-class-list.c
        libnl/src/nl-classid-lookup.c
        libnl/src/nl-cls-add.c
        libnl/src/nl-cls-delete.c
        libnl/src/nl-cls-list.c
        libnl/src/nl-fib-lookup.c
        libnl/src/nl-link-enslave.c
        libnl/src/nl-link-ifindex2name.c
        libnl/src/nl-link-list.c
        libnl/src/nl-link-name2ifindex.c
        libnl/src/nl-link-release.c
        libnl/src/nl-link-set.c
        libnl/src/nl-link-stats.c
        libnl/src/nl-list-caches.c
        libnl/src/nl-list-sockets.c
        libnl/src/nl-monitor.c
        libnl/src/nl-neigh-add.c
        libnl/src/nl-neigh-delete.c
        libnl/src/nl-neigh-list.c
        libnl/src/nl-neightbl-list.c
        libnl/src/nl-link-name2ifindex.c
        libnl/src/nl-pktloc-lookup.c
        libnl/src/nl-qdisc-add.c
        libnl/src/nl-qdisc-delete.c
        libnl/src/nl-qdisc-list.c
        libnl/src/nl-route-add.c
        libnl/src/nl-route-delete.c
        libnl/src/nl-route-get.c
        libnl/src/nl-route-list.c
        libnl/src/nl-rule-list.c
        libnl/src/nl-link-release.c
        libnl/src/nl-tctree-list.c
        libnl/src/nl-util-addr.c
  )

target_include_directories(libnl PUBLIC
        "${CMAKE_CURRENT_SOURCE_DIR}/libnl/include"
        "${CMAKE_CURRENT_SOURCE_DIR}/libnl/lib"
        "${CMAKE_CURRENT_SOURCE_DIR}/libnl"
        )

target_compile_definitions(libnl PRIVATE
        -D_GNU_SOURCE
        -DPKGLIBDIR="/usr/bin/libnl"
        -DSYSCONFDIR="/usr/bin/libnl"
        )