add_executable(openvpn
        openvpn/config.h
        openvpn/include/openvpn-msg.h
        openvpn/include/openvpn-plugin.h
        openvpn/src/compat/compat.h
        openvpn/src/compat/compat-basename.c
        openvpn/src/compat/compat-daemon.c
        openvpn/src/compat/compat-dirname.c
        openvpn/src/compat/compat-gettimeofday.c
        openvpn/src/compat/compat-strsep.c
        openvpn/src/openvpn/argv.c
        openvpn/src/openvpn/argv.h
        openvpn/src/openvpn/auth_token.c
        openvpn/src/openvpn/auth_token.h
        openvpn/src/openvpn/base64.c
        openvpn/src/openvpn/base64.h
        openvpn/src/openvpn/basic.h
        openvpn/src/openvpn/block_dns.c
        openvpn/src/openvpn/block_dns.h
        openvpn/src/openvpn/buffer.c
        openvpn/src/openvpn/buffer.h
        openvpn/src/openvpn/circ_list.h
        openvpn/src/openvpn/clinat.c
        openvpn/src/openvpn/clinat.h
        openvpn/src/openvpn/common.h
        openvpn/src/openvpn/comp.c
        openvpn/src/openvpn/comp.h
        openvpn/src/openvpn/comp-lz4.c
        openvpn/src/openvpn/comp-lz4.h
        openvpn/src/openvpn/compstub.c
        openvpn/src/openvpn/console.c
        openvpn/src/openvpn/console.h
        openvpn/src/openvpn/console_builtin.c
        openvpn/src/openvpn/console_systemd.c
        openvpn/src/openvpn/crypto.c
        openvpn/src/openvpn/crypto.h
        openvpn/src/openvpn/crypto_backend.h
        openvpn/src/openvpn/crypto_mbedtls.c
        #openvpn/src/openvpn/crypto_mbedtls.h
        openvpn/src/openvpn/crypto_openssl.c
        openvpn/src/openvpn/crypto_openssl.h
        openvpn/src/openvpn/cryptoapi.c
        openvpn/src/openvpn/cryptoapi.h
        openvpn/src/openvpn/dco.c
        openvpn/src/openvpn/dco.h
        openvpn/src/openvpn/dco_freebsd.c
        openvpn/src/openvpn/dco_freebsd.h
        openvpn/src/openvpn/dco_internal.h
        openvpn/src/openvpn/dco_linux.c
        openvpn/src/openvpn/dco_linux.h
        openvpn/src/openvpn/dco_win.c
        openvpn/src/openvpn/dco_win.h
        openvpn/src/openvpn/dhcp.c
        openvpn/src/openvpn/dhcp.h
        openvpn/src/openvpn/dns.c
        openvpn/src/openvpn/dns.h
        openvpn/src/openvpn/env_set.c
        openvpn/src/openvpn/env_set.h
        openvpn/src/openvpn/errlevel.h
        openvpn/src/openvpn/error.c
        openvpn/src/openvpn/error.h
        openvpn/src/openvpn/event.c
        openvpn/src/openvpn/event.h
        openvpn/src/openvpn/fdmisc.c
        openvpn/src/openvpn/fdmisc.h
        openvpn/src/openvpn/forward.c
        openvpn/src/openvpn/forward.h
        openvpn/src/openvpn/fragment.c
        openvpn/src/openvpn/fragment.h
        openvpn/src/openvpn/gremlin.c
        openvpn/src/openvpn/gremlin.h
        openvpn/src/openvpn/helper.c
        openvpn/src/openvpn/helper.h
        openvpn/src/openvpn/httpdigest.c
        openvpn/src/openvpn/httpdigest.h
        openvpn/src/openvpn/init.c
        openvpn/src/openvpn/init.h
        openvpn/src/openvpn/integer.h
        openvpn/src/openvpn/interval.c
        openvpn/src/openvpn/interval.h
        openvpn/src/openvpn/list.c
        openvpn/src/openvpn/list.h
        openvpn/src/openvpn/lladdr.c
        openvpn/src/openvpn/lladdr.h
        openvpn/src/openvpn/lzo.c
        openvpn/src/openvpn/lzo.h
        openvpn/src/openvpn/manage.c
        openvpn/src/openvpn/manage.h
        openvpn/src/openvpn/mbuf.c
        openvpn/src/openvpn/mbuf.h
        openvpn/src/openvpn/memdbg.h
        openvpn/src/openvpn/misc.c
        openvpn/src/openvpn/misc.h
        openvpn/src/openvpn/mroute.c
        openvpn/src/openvpn/mroute.h
        openvpn/src/openvpn/mss.c
        openvpn/src/openvpn/mss.h
        openvpn/src/openvpn/mstats.c
        openvpn/src/openvpn/mstats.h
        openvpn/src/openvpn/mtcp.c
        openvpn/src/openvpn/mtcp.h
        openvpn/src/openvpn/mtu.c
        openvpn/src/openvpn/mtu.h
        openvpn/src/openvpn/mudp.c
        openvpn/src/openvpn/mudp.h
        openvpn/src/openvpn/multi.c
        openvpn/src/openvpn/multi.h
        openvpn/src/openvpn/networking.h
        openvpn/src/openvpn/networking_freebsd.c
        openvpn/src/openvpn/networking_iproute2.c
        openvpn/src/openvpn/networking_iproute2.h
        openvpn/src/openvpn/networking_sitnl.c
        openvpn/src/openvpn/networking_sitnl.h
        openvpn/src/openvpn/ntlm.c
        openvpn/src/openvpn/ntlm.h
        openvpn/src/openvpn/occ.c
        openvpn/src/openvpn/occ.h
        openvpn/src/openvpn/openssl_compat.h
        openvpn/src/openvpn/openvpn.c
        openvpn/src/openvpn/openvpn.h
        openvpn/src/openvpn/options.c
        openvpn/src/openvpn/options.h
        openvpn/src/openvpn/options_util.c
        openvpn/src/openvpn/options_util.h
        openvpn/src/openvpn/otime.c
        openvpn/src/openvpn/otime.h
        openvpn/src/openvpn/ovpn_dco_freebsd.h
        openvpn/src/openvpn/ovpn_dco_linux.h
        openvpn/src/openvpn/ovpn_dco_win.h
        openvpn/src/openvpn/packet_id.c
        openvpn/src/openvpn/packet_id.h
        openvpn/src/openvpn/perf.c
        openvpn/src/openvpn/perf.h
        openvpn/src/openvpn/ping.c
        openvpn/src/openvpn/ping.h
        openvpn/src/openvpn/pkcs11.c
        openvpn/src/openvpn/pkcs11.h
        openvpn/src/openvpn/pkcs11_backend.h
        openvpn/src/openvpn/pkcs11_mbedtls.c
        openvpn/src/openvpn/pkcs11_openssl.c
        openvpn/src/openvpn/platform.c
        openvpn/src/openvpn/platform.h
        openvpn/src/openvpn/plugin.c
        openvpn/src/openvpn/plugin.h
        openvpn/src/openvpn/pool.c
        openvpn/src/openvpn/pool.h
        openvpn/src/openvpn/proto.c
        openvpn/src/openvpn/proto.h
        openvpn/src/openvpn/proxy.c
        openvpn/src/openvpn/proxy.h
        openvpn/src/openvpn/ps.c
        openvpn/src/openvpn/ps.h
        openvpn/src/openvpn/push.c
        openvpn/src/openvpn/push.h
        openvpn/src/openvpn/pushlist.h
        openvpn/src/openvpn/reflect_filter.c
        openvpn/src/openvpn/reflect_filter.h
        openvpn/src/openvpn/reliable.c
        openvpn/src/openvpn/reliable.h
        openvpn/src/openvpn/ring_buffer.h
        openvpn/src/openvpn/route.c
        openvpn/src/openvpn/route.h
        openvpn/src/openvpn/run_command.c
        openvpn/src/openvpn/run_command.h
        openvpn/src/openvpn/schedule.c
        openvpn/src/openvpn/schedule.h
        openvpn/src/openvpn/session_id.c
        openvpn/src/openvpn/session_id.h
        openvpn/src/openvpn/shaper.c
        openvpn/src/openvpn/shaper.h
        openvpn/src/openvpn/sig.c
        openvpn/src/openvpn/sig.h
        openvpn/src/openvpn/socket.c
        openvpn/src/openvpn/socket.h
        openvpn/src/openvpn/socks.c
        openvpn/src/openvpn/socks.h
        openvpn/src/openvpn/ssl.c
        openvpn/src/openvpn/ssl.h
        openvpn/src/openvpn/ssl_backend.h
        openvpn/src/openvpn/ssl_common.h
        openvpn/src/openvpn/ssl_mbedtls.c
        #openvpn/src/openvpn/ssl_mbedtls.h
        openvpn/src/openvpn/ssl_ncp.c
        openvpn/src/openvpn/ssl_ncp.h
        openvpn/src/openvpn/ssl_openssl.c
        openvpn/src/openvpn/ssl_openssl.h
        openvpn/src/openvpn/ssl_pkt.c
        openvpn/src/openvpn/ssl_pkt.h
        openvpn/src/openvpn/ssl_util.c
        openvpn/src/openvpn/ssl_util.h
        openvpn/src/openvpn/ssl_verify.c
        openvpn/src/openvpn/ssl_verify.h
        openvpn/src/openvpn/ssl_verify_backend.h
        openvpn/src/openvpn/ssl_verify_mbedtls.c
        openvpn/src/openvpn/ssl_verify_openssl.c
        openvpn/src/openvpn/ssl_verify_openssl.h
        openvpn/src/openvpn/status.c
        openvpn/src/openvpn/status.h
        openvpn/src/openvpn/syshead.h
        openvpn/src/openvpn/tls_crypt.c
        openvpn/src/openvpn/tls_crypt.h
        openvpn/src/openvpn/tun.c
        openvpn/src/openvpn/tun.h
        openvpn/src/openvpn/vlan.c
        openvpn/src/openvpn/vlan.h
        openvpn/src/openvpn/win32.c
        openvpn/src/openvpn/win32.h
        openvpn/src/openvpn/win32-util.c
        openvpn/src/openvpn/win32-util.h
        openvpn/src/openvpn/xkey_common.h
        openvpn/src/openvpn/xkey_helper.c
        openvpn/src/openvpn/xkey_provider.c
        )

target_include_directories(openvpn PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/openvpn/include"
        "${CMAKE_CURRENT_SOURCE_DIR}/openvpn/src/compat"
        "${CMAKE_CURRENT_SOURCE_DIR}/openvpn"
        )

target_compile_definitions(openvpn PRIVATE
        -DHAVE_CONFIG_H
        -DENABLE_CRYPTO_OPENSSL=1
        -DCONFIGURE_GIT_FLAGS=\"\"
        -DOPENSSL_API_COMPAT=0x11000000L
        -DENABLE_CRYPTO_OPENSSL=1
        )

target_link_libraries(openvpn libnl openssl lzo lz4)